import {describe,expect,it} from 'vitest';
import {bossGate,chapterUnlocked,completeCampaignRun,createAdventureSave,currentCampaignChapter,discardItem,equipItem,buyItem,createBattle,openCampaignChest,repairCampaignProgress,resolveCorrect,resolveCounter} from './index';
import type {AdventureDefinition} from './types';

const sprite={id:'test',src:'assets/sprites/test.png',label:'Test'};
const definition:AdventureDefinition={id:'vocabulary',title:'Test',subtitle:'Test',status:'released',theme:{primary:'#fff',secondary:'#fff',surface:'#000',background:'#000',accent:'#fff'},currency:{id:'coin',name:'Münzen',sprite},merchant:{id:'merchant',name:'Händler',shopTitle:'Shop',greeting:'Hallo',note:'Test',portrait:'scholar',backdrop:'library',shelfNames:['Regal'],colors:{skin:'#fff',outfit:'#000',accent:'#fff'}},ranks:[{id:'one',title:'Eins',xp:0}],slots:{weapon:'Waffe'},items:[{id:'sword',name:'Schwert',slot:'weapon',tier:1,cost:10,power:2,defense:0,luck:0,visual:{id:'sword',style:'knightly',variant:1,primary:'#777',secondary:'#aaa',highlight:'#fff'}}],enemies:[{id:'slime',name:'Schleim',place:'Wiese',hp:20,attack:5,reward:5,xp:2,rule:'heal-on-miss',sprite}],modes:[{id:'test',title:'Test',description:'Test'}],questionProvider:{next:()=>({id:'q',inputKind:'choice',prompt:'A',choices:['B'],answer:'B',hintSteps:[]}),evaluate:(q,a)=>q.answer===a},world:{id:'world',width:100,height:100,start:{x:1,y:1},obstacles:[],encounters:[],merchant:{x:1,y:1},chest:{x:1,y:1}},achievements:[]};

const campaignDefinition:AdventureDefinition={...definition,enemies:[...definition.enemies,{id:'elite-vocabulary-1',name:'Elite',place:'Kapitel 1',hp:1,attack:1,reward:1,xp:1,rule:'normal',sprite},{id:'boss-vocabulary-1',name:'Boss',place:'Kapitel 1',hp:1,attack:1,reward:1,xp:1,rule:'normal',sprite}],campaign:[{id:'chapter-vocabulary-1',index:1,title:'Kapitel 1',topic:'Thema',itemTier:1,missions:[{id:'mission-vocabulary-1-1',title:'Mission 1',modeId:'test',reward:5,xp:2}],eliteEnemyId:'elite-vocabulary-1',bossEnemyId:'boss-vocabulary-1',chestId:'chest-vocabulary-1',minimumPower:3,minimumDefense:4,reward:10},{id:'chapter-vocabulary-2',index:2,title:'Kapitel 2',topic:'Weiter',itemTier:1,missions:[],eliteEnemyId:'elite-vocabulary-2',bossEnemyId:'boss-vocabulary-2',chestId:'chest-vocabulary-2',minimumPower:3,minimumDefense:4,reward:10}]};

describe('learning engine',()=>{
  it('removes equipped items safely after confirmation in the UI',()=>{let save={...createAdventureSave(definition),currency:20};save=buyItem(save,definition,'sword');expect(save.currency).toBe(10);save=equipItem(save,definition,'sword');const discarded=discardItem(save,'sword');expect(discarded.ownedItemIds).not.toContain('sword');expect(discarded.equippedBySlot.weapon).toBeUndefined();});
  it('applies shared battle rules',()=>{const enemy=definition.enemies[0];let battle=createBattle(enemy,0);battle={...battle,phase:'question'};const hit=resolveCorrect(battle,enemy,2);expect(hit.state.enemyHp).toBeLessThan(enemy.hp);const counter=resolveCounter(hit.state,enemy,0,true);expect(counter.state.enemyHp).toBeGreaterThanOrEqual(hit.state.enemyHp);});
  it('requires completed missions, a defeated elite, and enough equipment for the chapter boss',()=>{const chapter=campaignDefinition.campaign![0];let save=createAdventureSave(campaignDefinition);expect(bossGate(save,chapter,{power:9,defense:9})).toBe(false);save=completeCampaignRun(save,chapter,{missionId:chapter.missions[0].id});expect(bossGate(save,chapter,{power:9,defense:9})).toBe(false);save=completeCampaignRun(save,chapter,{target:'elite'});expect(bossGate(save,chapter,{power:2,defense:9})).toBe(false);expect(bossGate(save,chapter,{power:3,defense:3})).toBe(false);expect(bossGate(save,chapter,{power:3,defense:4})).toBe(true);});
  it('records campaign victories so the chest and next chapter unlock after a boss win',()=>{const [chapter,nextChapter]=campaignDefinition.campaign!;let save=createAdventureSave(campaignDefinition);save=completeCampaignRun(save,chapter,{missionId:chapter.missions[0].id});save=completeCampaignRun(save,chapter,{target:'elite'});save=completeCampaignRun(save,chapter,{target:'boss'});expect(save.campaign.defeatedBossIds).toContain(chapter.bossEnemyId);expect(chapterUnlocked(save,nextChapter)).toBe(true);save=openCampaignChest(save,chapter);expect(save.campaign.openedChestIds).toContain(chapter.chestId);});
  it('selects the first unlocked chapter whose boss is still open for the world map',()=>{const [chapter,nextChapter]=campaignDefinition.campaign!;let save=createAdventureSave(campaignDefinition);expect(currentCampaignChapter(save,campaignDefinition)).toBe(chapter);save=completeCampaignRun(save,chapter,{target:'boss'});expect(currentCampaignChapter(save,campaignDefinition)).toBe(nextChapter);});
  it('repairs campaign elites and bosses from the existing battle history',()=>{const save={...createAdventureSave(campaignDefinition),clearedEnemyIds:['elite-vocabulary-1','boss-vocabulary-1']};const repaired=repairCampaignProgress(save,campaignDefinition);expect(repaired.campaign.defeatedEliteIds).toContain('elite-vocabulary-1');expect(repaired.campaign.defeatedBossIds).toContain('boss-vocabulary-1');expect(repairCampaignProgress(repaired,campaignDefinition)).toBe(repaired);});
});
