import {useState} from 'react';
import type React from 'react';
import type {AdventureDefinition,AdventureSave,PlayerProfile} from '@lernhelden/engine';
import {buyItem,discardItem,equipItem,equipmentStats,rankFor,unequipSlot} from '@lernhelden/engine';
import {avatarSprite,Sprite} from './Sprite';
import {ItemSprite,MerchantPortrait} from './PixelArt';
import {Icon} from './Icon';

type Navigate=(path:string)=>void;

function Back({to,navigate}:{to:string;navigate:Navigate}){return <button className="back" onClick={()=>navigate(to)}><Icon name="arrow-left" size={18}/>Zurück</button>}
function PlayerAvatar({profile,size=150}:{profile:PlayerProfile;size?:number}){const index=Math.max(0,Number(profile.avatarPresetId.split('-')[1]||1)-1);return <div className="avatar"><Sprite sprite={avatarSprite(index)} size={size}/></div>}

export function InventoryScreen({adventure,save,profile,onSave,onEvent,navigate}:{adventure:AdventureDefinition;save:AdventureSave;profile:PlayerProfile;onSave:(save:AdventureSave)=>Promise<void>;onEvent:(type:'item-equipped')=>Promise<void>;navigate:Navigate}){
  const [selected,setSelected]=useState<string|null>(null);
  const [tab,setTab]=useState<'equipment'|'chest'>('equipment');
  const stats=equipmentStats(save,adventure);
  const equippedIds=new Set(Object.values(save.equippedBySlot));
  const chestItems=save.ownedItemIds.map(id=>adventure.items.find(item=>item.id===id)).filter((item):item is NonNullable<typeof item>=>Boolean(item&&!equippedIds.has(item.id)));
  const selectedItem=adventure.items.find(item=>item.id===selected);
  const equip=async(itemId:string)=>{const item=adventure.items.find(candidate=>candidate.id===itemId);if(!item)return;await onSave(equipItem(save,adventure,itemId));await onEvent('item-equipped');setSelected(null);setTab('equipment')};
  const remove=async(itemId:string)=>{const item=adventure.items.find(candidate=>candidate.id===itemId);if(!item)return;if(window.confirm(`„${item.name}“ wirklich dauerhaft löschen?\n\nEs gibt keine Rückerstattung.`)){await onSave(discardItem(save,itemId));setSelected(null)}};
  const dropIntoChest=(itemId:string)=>{const item=adventure.items.find(candidate=>candidate.id===itemId);if(item&&save.equippedBySlot[item.slot]===item.id)void onSave(unequipSlot(save,item.slot))};
  return <div className="page inventory-page arcane-inventory"><Back to={`/adventure/${adventure.id}`} navigate={navigate}/><p className="eyebrow">Ausrüstung anlegen und verwahren</p><h1>Charakterraum & Truhe</h1>
    <div className="mobile-tabs" role="tablist" aria-label="Inventarbereiche"><button role="tab" aria-selected={tab==='equipment'} onClick={()=>setTab('equipment')}>Ausrüstung</button><button role="tab" aria-selected={tab==='chest'} onClick={()=>setTab('chest')}>Truhe <span>{chestItems.length}</span></button></div>
    <section className="house-inventory">
      <article className={`character-room ${tab!=='equipment'?'mobile-panel-hidden':''}`}><div className="window-light"/><h2 className="character-name">{profile.displayName}</h2><div className="character-stage"><PlayerAvatar profile={profile} size={178}/><div className="slot-ring">{Object.entries(adventure.slots).map(([slot,label],index)=>{const item=adventure.items.find(candidate=>candidate.id===save.equippedBySlot[slot]);const valid=selectedItem?.slot===slot;return <button key={slot} data-slot={slot} style={{'--slot-index':index} as React.CSSProperties} draggable={Boolean(item)} className={`drop-slot ${item?'filled':''} ${valid?'drop-valid':''}`} onDragStart={event=>item&&event.dataTransfer.setData('text/plain',item.id)} onDragOver={event=>event.preventDefault()} onDrop={event=>void equip(event.dataTransfer.getData('text/plain'))} onClick={()=>selected&&valid&&void equip(selected)}>{item?<ItemSprite item={item} size={45}/>:<span className="empty-slot"/>}<span><strong>{label}</strong><small>{item?.name??'Leer'}</small></span>{item&&<span className="link" onClick={event=>{event.stopPropagation();void onSave(unequipSlot(save,slot))}}>Ablegen</span>}</button>})}</div></div><div className="stats inventory-stats"><span>{stats.power}<small>Stärke</small></span><span>{stats.defense}<small>Schutz</small></span><span>{stats.luck}<small>Glück</small></span></div><p className="help">Wähle in der Truhe ein Item. Der passende Platz wird hervorgehoben.</p></article>
      <article className={`chest-room ${tab!=='chest'?'mobile-panel-hidden':''}`} onDragOver={event=>event.preventDefault()} onDrop={event=>dropIntoChest(event.dataTransfer.getData('text/plain'))}><div className="chest-lid"/><div className="chest-title"><h2>Meine Truhe</h2><small>{chestItems.length} Gegenstände</small></div><div className="chest-grid">{chestItems.length===0&&<p className="empty-chest">Die Truhe ist leer. Ausrüstung bekommst du im Shop.</p>}{chestItems.map(item=><article draggable key={item.id} onDragStart={event=>event.dataTransfer.setData('text/plain',item.id)} className={selected===item.id?'selected':''} onClick={()=>setSelected(current=>current===item.id?null:item.id)}><ItemSprite item={item} size={62}/><strong>{item.name}</strong><small>Stärke {item.power} · Schutz {item.defense} · Glück {item.luck}</small><button className="desktop-danger danger" onClick={event=>{event.stopPropagation();void remove(item.id)}}>Dauerhaft löschen</button></article>)}</div><button className="chest-shop-button" onClick={()=>navigate(`/adventure/${adventure.id}/shop`)}>Zum Händler</button></article>
    </section>
    {selectedItem&&<div className="item-action-sheet" role="dialog" aria-label={`Aktionen für ${selectedItem.name}`}><ItemSprite item={selectedItem} size={58}/><div><strong>{selectedItem.name}</strong><small>Stärke {selectedItem.power} · Schutz {selectedItem.defense} · Glück {selectedItem.luck}</small></div><button onClick={()=>void equip(selectedItem.id)}>Ausrüsten</button><button className="danger" onClick={()=>void remove(selectedItem.id)}>Löschen</button><button className="icon-button quiet" aria-label="Itemaktionen schließen" onClick={()=>setSelected(null)}><Icon name="close"/></button></div>}
  </div>;
}

export function ShopScreen({adventure,save,onSave,onEvent,navigate}:{adventure:AdventureDefinition;save:AdventureSave;onSave:(save:AdventureSave)=>Promise<void>;onEvent:(type:'item-bought')=>Promise<void>;navigate:Navigate}){
  const currentRank=rankFor(adventure,save.xp),rankTier=adventure.ranks.indexOf(currentRank)+1;
  const tiers=[...new Set(adventure.items.map(item=>item.tier))];
  const [slot,setSlot]=useState('all');
  const [openTier,setOpenTier]=useState(Math.max(...tiers.filter(value=>value<=rankTier),tiers[0]??1));
  const purchase=async(id:string)=>{const next=buyItem(save,adventure,id);if(next===save)return;await onSave(next);await onEvent('item-bought')};
  return <div className="page shop-page arcane-shop"><Back to={`/adventure/${adventure.id}`} navigate={navigate}/><div className="heading-row"><div><p className="eyebrow">Ausrüstung für dein Abenteuer</p><h1>{adventure.merchant.shopTitle}</h1></div><div className="wallet"><Sprite sprite={adventure.currency.sprite} size={44}/><strong>{save.currency}</strong><span>{adventure.currency.name}</span></div></div><section className={`merchant-shop ${adventure.merchant.backdrop}`}><div className="merchant-counter"><MerchantPortrait merchant={adventure.merchant}/><div className="merchant-speech"><strong>{adventure.merchant.name}</strong><p>{adventure.merchant.greeting}</p><small>{currentRank.title} · {save.xp} Rangpunkte</small></div></div><div className="merchant-note">{adventure.merchant.note}</div><div className="shop-filters" aria-label="Ausrüstungsplatz filtern"><button className={slot==='all'?'active':''} onClick={()=>setSlot('all')}>Alles</button>{Object.entries(adventure.slots).map(([id,label])=><button className={slot===id?'active':''} key={id} onClick={()=>setSlot(id)}>{label}</button>)}</div>{tiers.map(itemTier=>{const expanded=openTier===itemTier;return <section className={`merchant-shelf ${itemTier>rankTier?'closed':'open'} ${expanded?'expanded':'collapsed'}`} key={itemTier}><button className="shelf-toggle" onClick={()=>setOpenTier(current=>current===itemTier?0:itemTier)} aria-expanded={expanded}><span><small>Regal {itemTier}</small><strong>{adventure.merchant.shelfNames[itemTier-1]??`Stufe ${itemTier}`}</strong></span><span>{itemTier>rankTier?`Ab Rang ${itemTier}`:'Geöffnet'}<Icon name="chevron-down"/></span></button><div className="shop-grid">{adventure.items.filter(item=>item.tier===itemTier&&(slot==='all'||item.slot===slot)).map(item=>{const owned=save.ownedItemIds.includes(item.id),locked=item.tier>rankTier;return <article key={item.id} className={locked?'locked':''}><ItemSprite item={item} size={76}/><div><small>Stufe {item.tier}</small><h3>{item.name}</h3><p>Stärke {item.power} · Schutz {item.defense} · Glück {item.luck}</p>{owned?<button disabled>Bereits in der Truhe</button>:locked?<button disabled>Ab Rang {item.tier}</button>:<button onClick={()=>void purchase(item.id)}>{item.cost} {adventure.currency.name}</button>}</div></article>})}</div></section>})}</section></div>;
}
