import {useEffect, useMemo, useRef, useState} from 'react';
import type {AdventureDefinition, AdventureId, AdventureSave, BattleState, PlayerProfile, Question} from '@lernhelden/engine';
import {applyAchievementEvent, battleAttacks, bossGate, buyItem, chapterComplete, chapterUnlocked, completeMission, createAdventureSave, createBattle, createProfile, defeatCampaignEnemy, discardItem, equipItem, equipmentStats, nextTurn, normalizeAdventureSave, openCampaignChest, rankFor, recordMastery, resolveCorrect, resolveCounter, selectAttack, touchSave, unequipSlot, upgradeCost, upgradeItem} from '@lernhelden/engine';
import {adventureById, adventures} from './adventures';
import {avatarSprite, Sprite, spriteUrl, uiSprites} from './components/Sprite';
import {ItemSprite, MerchantPortrait} from './components/PixelArt';
import {firebaseErrorMessage, FirebaseSaveRepository, login, logout, observeUser, register} from './persistence/firebase';
import {LocalSaveRepository} from './persistence/local';

type Screen = 'home'|'profile'|'adventure'|'campaign'|'inventory'|'shop'|'world'|'achievements'|'settings'|'battle';
type Route = {screen:Screen; adventureId?:AdventureId};

function readRoute():Route {
  const parts=location.hash.replace(/^#\/?/,'').split('/').filter(Boolean);
  if(parts[0]==='profile')return{screen:'profile'};
  if(parts[0]==='achievements')return{screen:'achievements'};
  if(parts[0]==='settings')return{screen:'settings'};
  if(parts[0]==='adventure'&&parts[1] in adventureById)return{screen:(parts[2] as Screen)||'adventure',adventureId:parts[1] as AdventureId};
  return{screen:'home'};
}

const go=(path:string)=>{location.hash=path.startsWith('/')?path:`/${path}`;};
const within=<T,>(promise:Promise<T>,milliseconds:number)=>new Promise<T>((resolve,reject)=>{const timer=window.setTimeout(()=>reject(new Error('timeout')),milliseconds);promise.then(value=>{clearTimeout(timer);resolve(value)},error=>{clearTimeout(timer);reject(error)})});
const cachedJson=<T,>(key:string):T|null=>{try{const value=localStorage.getItem(key);return value?JSON.parse(value) as T:null}catch{return null}};

export function App(){
  const demoMode=import.meta.env.VITE_E2E_MODE==='true';
  const [user,setUser]=useState<import('firebase/auth').User|null|undefined>(demoMode?({uid:'e2e'} as import('firebase/auth').User):undefined);
  const [profile,setProfile]=useState<PlayerProfile|null>(null);
  const [saves,setSaves]=useState<Partial<Record<AdventureId,AdventureSave>>>({});
  const [route,setRoute]=useState<Route>(readRoute);
  const [busy,setBusy]=useState(true);
  const [message,setMessage]=useState('');
  const repository=useMemo(()=>user?(demoMode?new LocalSaveRepository():new FirebaseSaveRepository(user)):null,[demoMode,user]);

  useEffect(()=>demoMode?undefined:observeUser(setUser),[demoMode]);
  useEffect(()=>{const listener=()=>setRoute(readRoute());window.addEventListener('hashchange',listener);return()=>window.removeEventListener('hashchange',listener)},[]);
  useEffect(()=>{
    if(!user||!repository){setBusy(false);setProfile(null);setSaves({});return;}
    let active=true;setBusy(true);
    const initialize=async()=>{
      try{
        const migrated=await within(repository.migrateLegacy(),6000);
        const loaded=Object.fromEntries(await Promise.all(adventures.map(async adventure=>[adventure.id,(await within(repository.loadAdventure(adventure.id),2500))??createAdventureSave(adventure)])));
        if(active){setProfile(migrated);setSaves(loaded);setBusy(false);}
      }catch(error){
        const fallbackProfile=cachedJson<PlayerProfile>('lernhelden:profile:v1')??createProfile();
        const fallbackSaves=Object.fromEntries(adventures.map(adventure=>[adventure.id,normalizeAdventureSave(cachedJson<AdventureSave>(`lernhelden:adventure:${adventure.id}:v1`),adventure)]));
        if(active){setProfile(fallbackProfile);setSaves(fallbackSaves);setMessage(firebaseErrorMessage(error));setBusy(false);}
      }
    };
    void initialize();
    return()=>{active=false};
  },[user,repository]);
  useEffect(()=>{document.documentElement.dataset.uiScale=profile?.settings.uiScale??'normal';document.documentElement.classList.toggle('reduced-motion',Boolean(profile?.settings.reducedMotion));},[profile?.settings]);

  const saveProfile=async(next:PlayerProfile)=>{setProfile(next);try{await repository?.saveProfile(next)}catch{setMessage('Änderung lokal gespeichert – Cloud folgt später.')}};
  const saveAdventure=async(next:AdventureSave)=>{setSaves(current=>({...current,[next.adventureId]:next}));try{await repository?.saveAdventure(next)}catch{setMessage('Fortschritt lokal gespeichert – Cloud folgt später.')}};
  const dispatchEvent=async(adventure:AdventureDefinition,type:Parameters<typeof applyAchievementEvent>[2]['type'])=>{if(!profile)return;await saveProfile(applyAchievementEvent(profile,adventure,{type,adventureId:adventure.id} as never));};

  if(user===undefined||busy)return <Loading/>;
  if(!user)return <AuthScreen message={message}/>;
  if(!profile)return <Loading/>;
  if(!profile.displayName)return <ProfileEditor profile={profile} onSave={saveProfile} firstRun/>;
  const adventure=route.adventureId?adventureById[route.adventureId]:undefined;
  const save=adventure?saves[adventure.id]??createAdventureSave(adventure):undefined;
  return <div className="app" style={adventure?{'--primary':adventure.theme.primary,'--accent':adventure.theme.accent,'--surface':adventure.theme.surface,'--background':adventure.theme.background} as React.CSSProperties:undefined}>
    <Header profile={profile} adventure={adventure} save={save} onLogout={()=>void logout()}/>
    {message&&<button className="notice" onClick={()=>setMessage('')}>{message}</button>}
    <main>
      {route.screen==='home'&&<PlatformHome profile={profile}/>}
      {route.screen==='profile'&&<ProfileEditor profile={profile} onSave={saveProfile}/>}
      {route.screen==='achievements'&&<Achievements profile={profile}/>}
      {route.screen==='settings'&&<Settings profile={profile} onSave={saveProfile}/>}
      {adventure&&save&&route.screen==='adventure'&&<button className="campaign-shortcut" onClick={()=>go(`/adventure/${adventure.id}/campaign`)}>24-Wochen-Kampagne öffnen</button>}
      {adventure&&save&&route.screen==='adventure'&&<AdventureHome adventure={adventure} save={save} profile={profile}/>}
      {adventure&&save&&route.screen==='campaign'&&<Campaign adventure={adventure} save={save} onSave={saveAdventure}/>}
      {adventure&&save&&route.screen==='inventory'&&<Inventory adventure={adventure} save={save} profile={profile} onSave={saveAdventure} onEvent={type=>dispatchEvent(adventure,type)}/>}
      {adventure&&save&&route.screen==='shop'&&<Shop adventure={adventure} save={save} onSave={saveAdventure} onEvent={type=>dispatchEvent(adventure,type)}/>}
      {adventure&&save&&route.screen==='world'&&<World adventure={adventure} save={save} profile={profile} onSave={saveAdventure}/>}
      {adventure&&save&&route.screen==='battle'&&<Battle adventure={adventure} initialSave={save} profile={profile} onSave={saveAdventure} onProfile={saveProfile}/>}
    </main>
  </div>;
}

function Loading(){return <div className="loading"><div className="pixel-loader"/><h1>Lernhelden</h1><p>Deine Abenteuer werden vorbereitet …</p></div>}

function AuthScreen({message}:{message:string}){
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [feedback,setFeedback]=useState(message);const [busy,setBusy]=useState(false);
  const submit=async(create:boolean)=>{if(!email||password.length<6){setFeedback('Bitte E-Mail und ein Passwort mit mindestens 6 Zeichen eingeben.');return}setBusy(true);try{if(create)await register(email,password);else await login(email,password)}catch(error){setFeedback((error as {code?:string}).code==='auth/invalid-credential'?'E-Mail oder Passwort stimmt nicht.':'Die Anmeldung hat nicht funktioniert.')}finally{setBusy(false)}};
  return <div className="auth-page"><section className="auth-card"><div className="logo-lockup"><Sprite sprite={uiSprites.map} size={76}/><div><span>Eine Welt. Viele Abenteuer.</span><h1>Lernhelden</h1></div></div><p>Melde dich einmal an und spiele Brüche, Dezimalzahlen und Vokabeln mit demselben Helden.</p><label>E-Mail<input type="email" value={email} onChange={event=>setEmail(event.target.value)} autoComplete="email"/></label><label>Passwort<input type="password" value={password} onChange={event=>setPassword(event.target.value)} onKeyDown={event=>event.key==='Enter'&&void submit(false)} autoComplete="current-password"/></label><div className="button-row"><button disabled={busy} onClick={()=>void submit(false)}>Anmelden</button><button className="secondary" disabled={busy} onClick={()=>void submit(true)}>Konto erstellen</button></div><p className="feedback" role="alert">{feedback}</p></section></div>;
}

function Header({profile,adventure,save,onLogout}:{profile:PlayerProfile;adventure?:AdventureDefinition;save?:AdventureSave;onLogout:()=>void}){
  const rank=adventure&&save?rankFor(adventure,save.xp):null;
  return <header className="topbar"><button className="brand" onClick={()=>go('/home')}><Sprite sprite={uiSprites.map} size={38}/><span>Lernhelden</span></button><nav>{adventure&&save&&<><button onClick={()=>go(`/adventure/${adventure.id}`)}>{adventure.title}</button><span>{rank?.title}</span><span className="currency"><Sprite sprite={adventure.currency.sprite} size={25}/>{save.currency}</span></>}<button onClick={()=>go('/achievements')}>Erfolge</button><button onClick={()=>go('/settings')}>Einstellungen</button><button onClick={()=>go('/profile')}>{profile.displayName}</button><button className="quiet" onClick={onLogout}>Abmelden</button></nav></header>;
}

function PlatformHome({profile}:{profile:PlayerProfile}){return <div className="page home-page"><section className="platform-hero"><div><p className="eyebrow">Dein großes Lern-Rollenspiel</p><h1>Willkommen, {profile.displayName}!</h1><p>Ein Held, eine Spielwelt und immer neue Lernabenteuer.</p></div><Avatar profile={profile} size={160}/></section><h2>Wähle dein Abenteuer</h2><section className="adventure-grid">{adventures.filter(item=>item.status!=='hidden').map(adventure=><article className="adventure-card" style={{'--card-color':adventure.theme.primary} as React.CSSProperties} key={adventure.id}><Sprite sprite={adventure.enemies[adventure.enemies.length-1].sprite} size={100}/><span className="status">{adventure.status==='beta'?'Beta':'Bereit'}</span><h2>{adventure.title}</h2><p>{adventure.subtitle}</p><button onClick={()=>go(`/adventure/${adventure.id}`)}>Abenteuer betreten →</button></article>)}</section></div>}

function ProfileEditor({profile,onSave,firstRun=false}:{profile:PlayerProfile;onSave:(value:PlayerProfile)=>Promise<void>;firstRun?:boolean}){const [name,setName]=useState(profile.displayName);const [avatar,setAvatar]=useState(Number(profile.avatarPresetId.split('-')[1]||1)-1);return <div className="page narrow"><p className="eyebrow">{firstRun?'Dein erster Schritt':'Gemeinsames Profil'}</p><h1>Gestalte deinen Lernhelden</h1><label className="field">Heldenname<input maxLength={24} value={name} onChange={event=>setName(event.target.value)}/></label><div className="avatar-picker">{Array.from({length:6},(_,index)=><button key={index} className={avatar===index?'selected':''} onClick={()=>setAvatar(index)}><Sprite sprite={avatarSprite(index)} size={88}/><span>Vorlage {index+1}</span></button>)}</div><button disabled={!name.trim()} onClick={()=>void onSave({...profile,displayName:name.trim(),avatarPresetId:`avatar-${avatar+1}`,clientUpdatedAt:Date.now()}).then(()=>go('/home'))}>Profil speichern</button></div>}

function Avatar({profile,size=120}:{profile:PlayerProfile;size?:number}){const index=Math.max(0,Number(profile.avatarPresetId.split('-')[1]||1)-1);return <div className="avatar"><Sprite sprite={avatarSprite(index)} size={size}/></div>}
const modeSprite=(index:number)=>[uiSprites.map,uiSprites.chest,uiSprites.achievement,uiSprites.shop][index%4];

function AdventureHome({adventure,save,profile}:{adventure:AdventureDefinition;save:AdventureSave;profile:PlayerProfile}){const stats=equipmentStats(save,adventure),rank=rankFor(adventure,save.xp);return <div className="page"><button className="back" onClick={()=>go('/home')}>← Alle Abenteuer</button><section className="adventure-hero"><div><p className="eyebrow">{rank.title}</p><h1>{adventure.title}</h1><p>{adventure.subtitle}</p><div className="stats"><span>{save.completed}<small>Aufgaben</small></span><span>{stats.power}<small>Stärke</small></span><span>{stats.defense}<small>Schutz</small></span></div></div><Avatar profile={profile} size={150}/></section><h2>Wähle dein Training</h2><section className="mode-grid">{adventure.modes.map((mode,index)=><article key={mode.id}><Sprite sprite={modeSprite(index)} size={52} className="mode-sprite"/><h3>{mode.title}</h3><p>{mode.description}</p><button onClick={()=>{sessionStorage.setItem(`lernhelden:mode:${adventure.id}`,mode.id);go(`/adventure/${adventure.id}/battle`)}}>Training starten</button></article>)}</section><section className="action-grid"><button onClick={()=>go(`/adventure/${adventure.id}/inventory`)}><Sprite sprite={uiSprites.chest} size={54}/>Inventar</button><button onClick={()=>go(`/adventure/${adventure.id}/shop`)}><Sprite sprite={uiSprites.shop} size={54}/>Shop</button><button onClick={()=>go(`/adventure/${adventure.id}/world`)}><Sprite sprite={uiSprites.map} size={54}/>Weltkarte</button></section></div>}

function Campaign({adventure,save,onSave}:{adventure:AdventureDefinition;save:AdventureSave;onSave:(save:AdventureSave)=>Promise<void>}){
  const stats=equipmentStats(save,adventure);
  const launch=(modeId:string,chapter:number,missionId?:string,target?:'elite'|'boss')=>{sessionStorage.setItem(`lernhelden:mode:${adventure.id}`,modeId);sessionStorage.setItem(`lernhelden:campaign:${adventure.id}`,JSON.stringify({chapter,missionId,target}));go(`/adventure/${adventure.id}/battle`)};
  return <div className="page"><button className="back" onClick={()=>go(`/adventure/${adventure.id}`)}>← Zurück</button><p className="eyebrow">24 Wochen · 12 Kapitel · keine Kalender-Sperre</p><h1>Deine Langzeitkampagne</h1><p>Meisterschaft und Fehlerwiederholung begleiten jedes Lernziel. Tages- und Wochenaufträge sind Bonus ohne Streak-Druck.</p><section className="campaign-grid">{(adventure.campaign ?? []).map(chapter=>{const unlocked=chapterUnlocked(save,chapter),done=chapterComplete(save,chapter),gate=bossGate(save,chapter,stats);return <article className={!unlocked?'locked':''} key={chapter.id}><small>Kapitel {chapter.index} · Itemstufe {chapter.itemTier}</small><h2>{chapter.topic}</h2><p>Boss: Stärke {chapter.minimumPower} · Schutz {chapter.minimumDefense}</p><div className="mission-list">{chapter.missions.map(mission=><button disabled={!unlocked||save.campaign.completedMissionIds.includes(mission.id)} key={mission.id} onClick={()=>launch(mission.modeId,chapter.index,mission.id)}>{save.campaign.completedMissionIds.includes(mission.id)?'✓ ':''}{mission.title}</button>)}</div><button disabled={!done||save.campaign.defeatedEliteIds.includes(chapter.eliteEnemyId)} onClick={()=>launch(chapter.missions[0].modeId,chapter.index,undefined,'elite')}>Elitekampf</button><button disabled={!gate||save.campaign.defeatedBossIds.includes(chapter.bossEnemyId)} onClick={()=>launch(chapter.missions[0].modeId,chapter.index,undefined,'boss')}>Kapitelboss</button><button disabled={!save.campaign.defeatedBossIds.includes(chapter.bossEnemyId)||save.campaign.openedChestIds.includes(chapter.chestId)} onClick={()=>void onSave(openCampaignChest(save,chapter))}>Schatztruhe +{chapter.reward}</button></article>})}</section></div>
}

function Inventory({adventure,save,profile,onSave,onEvent}:{adventure:AdventureDefinition;save:AdventureSave;profile:PlayerProfile;onSave:(save:AdventureSave)=>Promise<void>;onEvent:(type:'item-equipped')=>Promise<void>}){
  const [selected,setSelected]=useState<string|null>(null);const stats=equipmentStats(save,adventure);
  const equip=async(itemId:string,slot:string)=>{const item=adventure.items.find(candidate=>candidate.id===itemId);if(!item||item.slot!==slot)return;await onSave(equipItem(save,adventure,itemId));await onEvent('item-equipped');setSelected(null)};
  const remove=async(itemId:string)=>{const item=adventure.items.find(candidate=>candidate.id===itemId);if(!item)return;const accepted=window.confirm(`„${item.name}“ wirklich dauerhaft löschen?\n\nDer Gegenstand wird abgelegt, entfernt und es gibt keine Rückerstattung.`);if(accepted)await onSave(discardItem(save,itemId))};
  const equippedIds=new Set(Object.values(save.equippedBySlot));
  const chestItems=save.ownedItemIds.map(itemId=>adventure.items.find(item=>item.id===itemId)).filter(item=>item&&!equippedIds.has(item.id));
  const dropIntoChest=(itemId:string)=>{const item=adventure.items.find(candidate=>candidate.id===itemId);if(item&&save.equippedBySlot[item.slot]===item.id)void onSave(unequipSlot(save,item.slot))};
  return <div className="page inventory-page"><button className="back" onClick={()=>go(`/adventure/${adventure.id}`)}>← Zurück</button><p className="eyebrow">Ausrüstung anlegen und verwahren</p><h1>Charakterraum & Truhe</h1><section className="house-inventory"><article className="character-room"><div className="window-light"/><h2 className="character-name">{profile.displayName}</h2><div className="character-stage"><Avatar profile={profile} size={178}/><div className="slot-ring">{Object.entries(adventure.slots).map(([slot,label],index)=>{const item=adventure.items.find(candidate=>candidate.id===save.equippedBySlot[slot]);const valid=selected&&adventure.items.find(candidate=>candidate.id===selected)?.slot===slot;return <button key={slot} data-slot={slot} style={{'--slot-index':index} as React.CSSProperties} draggable={Boolean(item)} className={`drop-slot ${item?'filled':''} ${valid?'drop-valid':''}`} onDragStart={event=>item&&event.dataTransfer.setData('text/plain',item.id)} onDragOver={event=>event.preventDefault()} onDrop={event=>void equip(event.dataTransfer.getData('text/plain'),slot)} onClick={()=>selected&&void equip(selected,slot)}>{item?<ItemSprite item={item} size={45}/>:<span className="empty-slot"/>}<span><strong>{label}</strong><small>{item?.name??'Leer'}</small></span>{item&&<span className="link" onClick={event=>{event.stopPropagation();void onSave(unequipSlot(save,slot))}}>Ablegen</span>}</button>})}</div></div><div className="stats inventory-stats"><span>{stats.power}<small>Stärke</small></span><span>{stats.defense}<small>Schutz</small></span><span>{stats.luck}<small>Glück</small></span></div><p className="help">Ziehe ein Item auf den passenden Platz. Auf Touch-Geräten: Item und danach den leuchtenden Platz antippen.</p></article><article className="chest-room" onDragOver={event=>event.preventDefault()} onDrop={event=>dropIntoChest(event.dataTransfer.getData('text/plain'))}><div className="chest-lid"/><div className="chest-title"><h2>Meine Truhe</h2><small>{chestItems.length} Gegenstände</small></div><div className="chest-grid">{chestItems.length===0&&<p className="empty-chest">Die Truhe ist leer. Ausrüstung bekommst du im Shop.</p>}{chestItems.map(item=>item&&<article draggable key={item.id} onDragStart={event=>event.dataTransfer.setData('text/plain',item.id)} className={selected===item.id?'selected':''} onClick={()=>setSelected(current=>current===item.id?null:item.id)}><ItemSprite item={item} size={62}/><strong>{item.name}</strong><small>Stärke {item.power} · Schutz {item.defense} · Glück {item.luck}</small><button className="danger" onClick={event=>{event.stopPropagation();void remove(item.id)}}>Dauerhaft löschen</button></article>)}</div><button className="chest-shop-button" onClick={()=>go(`/adventure/${adventure.id}/shop`)}>Zum Händler</button></article></section></div>;
}

function Shop({adventure,save,onSave,onEvent}:{adventure:AdventureDefinition;save:AdventureSave;onSave:(save:AdventureSave)=>Promise<void>;onEvent:(type:'item-bought')=>Promise<void>}){const currentRank=rankFor(adventure,save.xp),tier=adventure.ranks.indexOf(currentRank)+1;const purchase=async(id:string)=>{const next=buyItem(save,adventure,id);if(next===save)return;await onSave(next);await onEvent('item-bought')};const tiers=[...new Set(adventure.items.map(item=>item.tier))];return <div className="page shop-page"><button className="back" onClick={()=>go(`/adventure/${adventure.id}`)}>← Zurück</button><div className="heading-row"><div><p className="eyebrow">Ausrüstung für dein Abenteuer</p><h1>{adventure.merchant.shopTitle}</h1></div><div className="wallet"><Sprite sprite={adventure.currency.sprite} size={44}/><strong>{save.currency}</strong><span>{adventure.currency.name}</span></div></div><section className={`merchant-shop ${adventure.merchant.backdrop}`}><div className="merchant-counter"><MerchantPortrait merchant={adventure.merchant}/><div className="merchant-speech"><strong>{adventure.merchant.name}</strong><p>{adventure.merchant.greeting}</p><small>{currentRank.title} · {save.xp} Rangpunkte</small></div></div><div className="merchant-note">{adventure.merchant.note}</div>{tiers.map(itemTier=><section className={`merchant-shelf ${itemTier>tier?'closed':'open'}`} key={itemTier}><header><div><span>Regal {itemTier}</span><h2>{adventure.merchant.shelfNames[itemTier-1]??`Stufe ${itemTier}`}</h2></div><strong>{itemTier>tier?`Ab Rang ${itemTier}`:'Geöffnet'}</strong></header><div className="shop-grid">{adventure.items.filter(item=>item.tier===itemTier).map(item=>{const owned=save.ownedItemIds.includes(item.id),locked=item.tier>tier;return <article key={item.id} className={locked?'locked':''}><ItemSprite item={item} size={76}/><div><small>Stufe {item.tier}</small><h3>{item.name}</h3><p>Stärke {item.power} · Schutz {item.defense} · Glück {item.luck}</p>{owned?<button disabled>Bereits in der Truhe</button>:locked?<button disabled>Ab Rang {item.tier}</button>:<button onClick={()=>void purchase(item.id)}>{item.cost} {adventure.currency.name}</button>}</div></article>})}</div></section>)}</section></div>}

function Battle({adventure,initialSave,profile,onSave,onProfile}:{adventure:AdventureDefinition;initialSave:AdventureSave;profile:PlayerProfile;onSave:(save:AdventureSave)=>Promise<void>;onProfile:(profile:PlayerProfile)=>Promise<void>}){
  const modeId=sessionStorage.getItem(`lernhelden:mode:${adventure.id}`)??adventure.modes[0].id;
  const campaignRun=JSON.parse(sessionStorage.getItem(`lernhelden:campaign:${adventure.id}`)??'null') as {chapter:number;missionId?:string;target?:'elite'|'boss'}|null;
  const chapter=campaignRun?(adventure.campaign ?? [])[campaignRun.chapter-1]:undefined;
  const enemy=chapter&&campaignRun?.target?adventure.enemies.find(candidate=>candidate.id===(campaignRun.target==='boss'?chapter.bossEnemyId:chapter.eliteEnemyId))??adventure.enemies[0]:adventure.enemies.find(candidate=>!initialSave.clearedEnemyIds.includes(candidate.id))??adventure.enemies[adventure.enemies.length-1];
  const stats=equipmentStats(initialSave,adventure);
  const [battle,setBattle]=useState<BattleState>(()=>createBattle(enemy,stats.defense));
  const [save,setSave]=useState(initialSave);const [question,setQuestion]=useState<Question|null>(null);const [answer,setAnswer]=useState('');const [feedback,setFeedback]=useState('');const [sequence,setSequence]=useState(0);
  const newQuestion=()=>{const nextSequence=sequence+1;setSequence(nextSequence);setQuestion(adventure.questionProvider.next({modeId,sequence:nextSequence,random:Math.random,chapter:chapter?.index,mastery:save.masteryByKey}));setAnswer('');setFeedback('')};
  const choose=(id:BattleState['selectedAttackId'])=>{const selected=selectAttack(battle,id);setBattle(selected);if(selected.phase==='question')newQuestion()};
  const persistEvent=async(next:AdventureSave,type:'answer-correct'|'answer-wrong'|'boss-defeated')=>{setSave(next);await onSave(next);await onProfile(applyAchievementEvent(profile,adventure,{type,adventureId:adventure.id}))};
  const submit=async()=>{
    if(!question)return;const correct=adventure.questionProvider.evaluate(question,answer);
    if(correct){const hit=resolveCorrect(battle,enemy,stats.power);let next=touchSave({...save,currency:save.currency+2+Math.floor(stats.luck/4),xp:save.xp+1,completed:save.completed+1,stats:{...save.stats,correct:save.stats.correct+1,bestStreak:Math.max(save.stats.bestStreak,hit.state.streak)}});setFeedback(`Richtig! ${hit.damage} Schaden.`);if(hit.state.phase==='won'){const first=!next.clearedEnemyIds.includes(enemy.id);next=touchSave({...next,currency:next.currency+(first?enemy.reward:Math.max(5,Math.floor(enemy.reward/8))),xp:next.xp+(first?enemy.xp:0),clearedEnemyIds:first?[...next.clearedEnemyIds,enemy.id]:next.clearedEnemyIds});setBattle(hit.state);await persistEvent(next,'boss-defeated');return}const counter=resolveCounter(hit.state,enemy,stats.defense,false);setBattle(counter.state);setFeedback(`Richtig! ${hit.damage} Schaden. ${enemy.name} kontert mit ${counter.damage}.`);await persistEvent(next,'answer-correct');}
    else{const counter=resolveCounter(battle,enemy,stats.defense,true);const next=touchSave({...save,stats:{...save.stats,wrong:save.stats.wrong+1}});setBattle(counter.state);setFeedback(`Noch nicht. Richtig ist ${question.answer}. ${enemy.name} trifft mit ${counter.damage}.`);await persistEvent(next,'answer-wrong')}
  };
  const continueBattle=()=>{setBattle(nextTurn(battle));setQuestion(null);setFeedback('')};
  return <div className="page battle-page"><button className="back" onClick={()=>go(`/adventure/${adventure.id}`)}>← Kampf verlassen</button><div className="battle-heading"><div><p className="eyebrow">{adventure.modes.find(mode=>mode.id===modeId)?.title}</p><h1>{enemy.name}</h1></div><span>{enemy.place}</span></div><section className="battle-stage"><div className="fighter"><Avatar profile={profile} size={105}/><strong>{profile.displayName}</strong><Health value={battle.playerHp} max={battle.playerMaxHp}/></div><div className="battle-center">gegen</div><div className="fighter"><Sprite sprite={enemy.sprite} size={118}/><strong>{enemy.name}</strong><Health value={battle.enemyHp} max={battle.enemyMaxHp}/></div></section>{battle.phase==='attack-select'&&<section><h2>Wähle deinen Angriff</h2><div className="attack-grid">{battleAttacks.map(attack=><button key={attack.id} disabled={(battle.cooldowns[attack.id]??0)>0} onClick={()=>choose(attack.id)}><Sprite sprite={attack.sprite} size={58}/><strong>{attack.name}</strong><small>{attack.id==='chain'?'Stärker mit Serie':`${attack.damage} Kraft · ${attack.cooldown} Abklingzeit`}</small></button>)}</div></section>}{battle.phase==='question'&&question&&<section className="question-card"><span>{question.category}</span><h2>{question.inputKind==='fraction'?<FractionExpression text={question.prompt}/>:question.prompt}</h2>{question.inputKind==='choice'?<div className="choice-grid">{question.choices?.map(choice=><button key={choice} onClick={()=>setAnswer(choice)} className={answer===choice?'selected':''}>{choice}</button>)}</div>:question.inputKind==='fraction'?<FractionInput value={answer} onChange={setAnswer}/>:<input className="answer-input" inputMode="decimal" value={answer} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>event.key==='Enter'&&void submit()}/>}<button disabled={!answer} onClick={()=>void submit()}>Antwort prüfen</button></section>}{(battle.phase==='resolved'||battle.phase==='won'||battle.phase==='lost')&&<section className={`result ${battle.phase}`}><h2>{battle.phase==='won'?'Sieg!':battle.phase==='lost'?'Dein Held braucht eine Pause':'Nächster Zug'}</h2><p>{feedback}</p>{battle.phase==='resolved'?<button onClick={continueBattle}>Weiterkämpfen</button>:<button onClick={()=>go(`/adventure/${adventure.id}/world`)}>Zur Weltkarte</button>}</section>}</div>;
}

function Health({value,max}:{value:number;max:number}){return <div className="health"><i style={{width:`${Math.max(0,100*value/max)}%`}}/><span>{value}/{max}</span></div>}
function FractionInput({value,onChange}:{value:string;onChange:(value:string)=>void}){const [top,bottom='']=value.split('/');return <div className="fraction-input"><input aria-label="Zähler" inputMode="numeric" value={top} onChange={event=>onChange(`${event.target.value}/${bottom}`)}/><span/><input aria-label="Nenner" inputMode="numeric" value={bottom} onChange={event=>onChange(`${top}/${event.target.value}`)}/></div>}
function FractionExpression({text}:{text:string}){return <span className="fraction-expression">{text.split(/(\d+\/\d+)/g).map((part,index)=>{const match=part.match(/^(\d+)\/(\d+)$/);return match?<span className="math-fraction" key={index}><i>{match[1]}</i><b/><i>{match[2]}</i></span>:<span key={index}>{part}</span>})}</span>}

function World({adventure,save,profile,onSave}:{adventure:AdventureDefinition;save:AdventureSave;profile:PlayerProfile;onSave:(save:AdventureSave)=>Promise<void>}){
  const canvasRef=useRef<HTMLCanvasElement>(null);const [position,setPosition]=useState(save.world);const [hint,setHint]=useState('Erkunde die Welt und finde den nächsten Gegner.');
  const move=(dx:number,dy:number)=>{const step=24,nx=Math.max(24,Math.min(adventure.world.width-24,position.x+dx*step)),ny=Math.max(64,Math.min(adventure.world.height-24,position.y+dy*step));const blocked=adventure.world.obstacles.some(obstacle=>nx+14>obstacle.x&&nx-14<obstacle.x+obstacle.width&&ny+14>obstacle.y&&ny-14<obstacle.y+obstacle.height);if(!blocked){const next={...position,x:nx,y:ny};setPosition(next);void onSave(touchSave({...save,world:next}))}};
  const interact=()=>{const encounter=adventure.world.encounters.find(item=>Math.hypot(item.x-position.x,item.y-position.y)<75);if(encounter){sessionStorage.setItem(`lernhelden:mode:${adventure.id}`,adventure.modes[0].id);go(`/adventure/${adventure.id}/battle`);return}if(Math.hypot(adventure.world.merchant.x-position.x,adventure.world.merchant.y-position.y)<75){go(`/adventure/${adventure.id}/shop`);return}if(Math.hypot(adventure.world.chest.x-position.x,adventure.world.chest.y-position.y)<75){go(`/adventure/${adventure.id}/inventory`);return}setHint('Gehe näher an einen Gegner, Händler oder die Truhe.')};
  useEffect(()=>{const key=(event:KeyboardEvent)=>{const moves:Record<string,[number,number]>={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]};const selected=moves[event.key.toLowerCase()];if(selected){event.preventDefault();move(...selected)}if(event.key==='Enter'||event.key.toLowerCase()==='e')interact()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const context=canvas.getContext('2d');if(!context)return;let active=true;context.imageSmoothingEnabled=false;const paintBackground=()=>{context.fillStyle=adventure.theme.background;context.fillRect(0,0,canvas.width,canvas.height);for(let x=0;x<canvas.width;x+=32)for(let y=0;y<canvas.height;y+=32){context.fillStyle=(x/32+y/32)%2?`${adventure.theme.primary}25`:`${adventure.theme.secondary}18`;context.fillRect(x,y,32,32)}context.fillStyle=adventure.theme.accent;context.fillRect(0,390,canvas.width,52);adventure.world.obstacles.forEach(obstacle=>{context.fillStyle=adventure.theme.surface;context.fillRect(obstacle.x,obstacle.y,obstacle.width,obstacle.height);context.fillStyle=adventure.theme.primary;context.fillRect(obstacle.x+6,obstacle.y+6,obstacle.width-12,12)})};const load=(source:string)=>new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=source});const paint=async()=>{paintBackground();const visible=adventure.world.encounters.map(entry=>({entry,enemy:adventure.enemies.find(candidate=>candidate.id===entry.enemyId)})).filter(value=>value.enemy&&!save.clearedEnemyIds.includes(value.enemy.id));const avatar=avatarSprite(Math.max(0,Number(profile.avatarPresetId.split('-')[1]||1)-1));const refs=[...visible.map(value=>value.enemy!.sprite),uiSprites.shop,uiSprites.chest,avatar];try{const images=await Promise.all(refs.map(ref=>load(spriteUrl(ref))));if(!active)return;const draw=(image:HTMLImageElement,x:number,y:number,size:number)=>context.drawImage(image,x-size/2,y-size/2,size,size);visible.forEach((value,index)=>draw(images[index],value.entry.x,value.entry.y,70));const offset=visible.length;draw(images[offset],adventure.world.merchant.x,adventure.world.merchant.y,58);draw(images[offset+1],adventure.world.chest.x,adventure.world.chest.y,58);draw(images[offset+2],position.x,position.y,68)}catch{if(active)paintBackground()}};void paint();return()=>{active=false}},[adventure,position,profile.avatarPresetId,save.clearedEnemyIds]);
  return <div className="page"><button className="back" onClick={()=>go(`/adventure/${adventure.id}`)}>← Zurück</button><div className="heading-row"><div><p className="eyebrow">Begehbare Pixelwelt</p><h1>{adventure.world.id.replaceAll('-',' ')}</h1></div><p>{hint}</p></div><div className="world-wrap"><canvas ref={canvasRef} width={960} height={540}/><div className="touch-controls"><button onClick={()=>move(0,-1)}>▲</button><span><button onClick={()=>move(-1,0)}>◀</button><button onClick={interact}>E</button><button onClick={()=>move(1,0)}>▶</button></span><button onClick={()=>move(0,1)}>▼</button></div></div></div>;
}

function Achievements({profile}:{profile:PlayerProfile}){return <div className="page"><button className="back" onClick={()=>go('/home')}>← Startseite</button><p className="eyebrow">Gemeinsam über alle Abenteuer</p><h1>Erfolge</h1><section className="achievement-grid">{adventures.flatMap(adventure=>adventure.achievements.map(achievement=>{const entry=profile.achievements[`${adventure.id}:${achievement.id}`];return <article key={`${adventure.id}:${achievement.id}`} className={entry?.unlockedAt?'unlocked':''}><Sprite sprite={achievement.sprite} size={64}/><small>{adventure.title}</small><h2>{achievement.title}</h2><p>{achievement.description}</p><progress value={entry?.progress??0} max={achievement.threshold}/><span>{entry?.progress??0}/{achievement.threshold}</span></article>}))}</section></div>}

function Settings({profile,onSave}:{profile:PlayerProfile;onSave:(profile:PlayerProfile)=>Promise<void>}){const update=(settings:Partial<PlayerProfile['settings']>)=>void onSave({...profile,settings:{...profile.settings,...settings},clientUpdatedAt:Date.now()});return <div className="page narrow"><button className="back" onClick={()=>go('/home')}>← Startseite</button><p className="eyebrow">Für alle Abenteuer</p><h1>Einstellungen</h1><section className="settings-card"><label><span><strong>Reduzierte Animationen</strong><small>Weniger Bewegung bei Angriffen und Übergängen.</small></span><input type="checkbox" checked={profile.settings.reducedMotion} onChange={event=>update({reducedMotion:event.target.checked})}/></label><label><span><strong>Steuerungshinweise</strong><small>Tasten und Touch-Hilfe auf der Weltkarte anzeigen.</small></span><input type="checkbox" checked={profile.settings.showControlHints} onChange={event=>update({showControlHints:event.target.checked})}/></label><label><span><strong>Vollbild bevorzugen</strong><small>Vollbild beim Start eines Abenteuers anbieten.</small></span><input type="checkbox" checked={profile.settings.fullscreenPreferred} onChange={event=>update({fullscreenPreferred:event.target.checked})}/></label><label><span><strong>Größe der Oberfläche</strong><small>Gilt auf diesem und allen anderen Geräten.</small></span><select value={profile.settings.uiScale} onChange={event=>update({uiScale:event.target.value as PlayerProfile['settings']['uiScale']})}><option value="small">Klein</option><option value="normal">Normal</option><option value="large">Groß</option></select></label></section><button onClick={()=>document.documentElement.requestFullscreen?.()}>Jetzt Vollbild öffnen</button></div>}
